### ISSUE TITLE
not working for me ...

### ISSUE THREAD

**Issue by breathe** [dbashford/mimosa-just-copy#1]
Sorry for a bit of a delay here.  I updated to mimosa 0.14.1 to try this --

I still see errors like this in subdirectories described in justCopy.paths

``` console
16:28:19 - No module has registered for extension: [[ pl ]], file: [[ /Users/ncohen/software/webdev/dryit-mimosa/assets/javascripts/vendor/bower_components/showdown/perlMarkdown/Markdown-1.0.2b2.pl ]]
16:28:19 - No module has registered for extension: [[ pl ]], file: [[ /Users/ncohen/software/webdev/dryit-mimosa/assets/javascripts/vendor/bower_components/showdown/perlMarkdown/Markdown-1.0.2b7.pl ]]
16:28:19 - No module has registered for extension: [[ php ]], file: [[ /Users/ncohen/software/webdev/dryit-mimosa/assets/javascripts/vendor/bower_components/uri.js/utils/SLDs.php ]]

```

On a side note -- I intend to look into the mimosa-bower option as majority of errors of this type are the result of crud hanging about from bower -- but for now I'd like to know this feature also behaves as expected ...  

I wasn't sure if maybe there was some magic associated with the 'javascripts/vendor' directory might be causing a problem -- so I also tried by copying the directory to javascripts/vendor2 and adjusting the justCopy.paths appropriate with the same result ...

Here's my mimosa config ...

``` coffeescript
# this coffeescript file generates a json object which configures the entirety of mimosa operation
# the below values are the only things changed from default -- comments describing the behavior of all fields
# and the default settings are located in mimosa-config-comments.coffee

exports.config = {

  # we use these mimosa modules
  modules: ['lint', 'client-jade-static', 'just-copy', 'server', 'minify', 'live-reload']

  # limit file watcher to 100 simultaneously open file handlers at a time -- since the files are processed
  # asynchronously, without this option file processing could otherwise open all the files at essentially
  # the same time on startup and could hit the os's file handle limit
  watch:
    throttle: 100
    #exclude: ["javascripts/vendor"]


  coffeescript:
    sourceMap:true
    bare:false

  template:
    amdWrap: false

    nameTransform: (path) ->
      m = path.match /templates?\/(.*)$/
      if m?.length and m.length == 2
        return m[1]
      path = path.split '/'
      return path[path.length - 1]

    outputFileName:
      handlebars:"compiled-handlebars"
      emblem:"compiled-emblem"

    handlebars:
      lib: require('handlebars')
      helpers:["app/handlebars-helpers"]
      ember:
        enabled: true
        path: "vendor/components/ember/ember.js"

  justCopy:
    paths:["javascripts/vendor"]

  copy:
    extensions: ["js","css","png","jpg","jpeg","gif","html","eot","svg","ttf","woff","otf","yaml","kml","ico","htc","htm","json","txt","xml","xsd","map","md"]

  server:
    views:
      compileWith: 'jade'
      extension: 'jade'
      path: 'views'
}
```

**Comment by dbashford** [comment]
If you add `pl` and `php` to the `copy.extensions` array, does it work?

Probably not ideal, but `just-copy` still works within the confines of what mimosa-core will process.  So if is not one of the default compiler extensions (like `coffee` or `scss`) and it is not in the `copy` array, mimosa disregards it.

Let me know if that works for ya.

Definitely give mimosa-bower a shot.  Just know that there are some big changes coming to that in the coming days.  Namely dbashford/mimosa-bower#7 and dbashford/mimosa-bower#6.

**Comment by breathe** [comment]
Ah ok I see.  I should be more clear that the module _does_ in fact work -- without using it I was getting some random files with an extension which mimosa understands processed from some of those directories with undesirable results as well as seeing lint errors generated from things in the various github repos.

For now I'll just add the extra "don't care" extensions to the copy array (I had taken them out actually to test the behavior of just-copy.

Thanks.

**Comment by dbashford** [comment]
You could add those things to `watch.exclude`.  `[/\.(pl|php)$/]`

**Comment by breathe** [comment]
Ah, that's nice.  Thanks!

**Comment by dbashford** [comment]
Several ways to skin the cat =)

So the problem you were having is essentially "working as expected".  There may be a time where this module evolves to not care whether or not Mimosa is aware of the extension, but not sure I'm there with it yet.

You cool with that?  Short term at least?  If so, worth closing this out?

**Comment by breathe** [comment]
Yeah this makes sense to me now.
